[package]
name = "tftp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
clap = "4"
scopeguard = "1"
num-traits = "0.2"
num-derive = "0.3"

[dev-dependencies]
assert_cmd = "2.0.7"
assert_fs  = "1"
predicates = "2.1.5"